// <auto-generated />
using System;
using Group4_FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group4_FinalProject.Migrations
{
    [DbContext(typeof(ElectronicsStoreContext))]
    partial class ElectronicsStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Group4_FinalProject.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            FirstName = "Michelle"
                        },
                        new
                        {
                            BrandId = 2,
                            FirstName = "Stephen E."
                        },
                        new
                        {
                            BrandId = 3,
                            FirstName = "Margaret"
                        },
                        new
                        {
                            BrandId = 4,
                            FirstName = "Jane",
                            LastName = "Austen"
                        },
                        new
                        {
                            BrandId = 5,
                            FirstName = "James"
                        },
                        new
                        {
                            BrandId = 6,
                            FirstName = "Emily",
                            LastName = "Bronte"
                        },
                        new
                        {
                            BrandId = 7,
                            FirstName = "Agatha"
                        },
                        new
                        {
                            BrandId = 8,
                            FirstName = "Ta-Nehisi"
                        },
                        new
                        {
                            BrandId = 9,
                            FirstName = "Jared"
                        },
                        new
                        {
                            BrandId = 10,
                            FirstName = "Joan"
                        },
                        new
                        {
                            BrandId = 11,
                            FirstName = "Daphne"
                        },
                        new
                        {
                            BrandId = 12,
                            FirstName = "Tina"
                        },
                        new
                        {
                            BrandId = 13,
                            FirstName = "Roxane"
                        },
                        new
                        {
                            BrandId = 14,
                            FirstName = "Dashiel"
                        },
                        new
                        {
                            BrandId = 15,
                            FirstName = "Frank",
                            LastName = "Herbert"
                        },
                        new
                        {
                            BrandId = 16,
                            FirstName = "Aldous"
                        },
                        new
                        {
                            BrandId = 17,
                            FirstName = "Stieg",
                            LastName = "Larsson"
                        },
                        new
                        {
                            BrandId = 18,
                            FirstName = "David"
                        },
                        new
                        {
                            BrandId = 19,
                            FirstName = "Toni"
                        },
                        new
                        {
                            BrandId = 20,
                            FirstName = "George"
                        },
                        new
                        {
                            BrandId = 21,
                            FirstName = "Mary"
                        },
                        new
                        {
                            BrandId = 22,
                            FirstName = "Sun"
                        },
                        new
                        {
                            BrandId = 23,
                            FirstName = "Augusten"
                        },
                        new
                        {
                            BrandId = 25,
                            FirstName = "JK"
                        },
                        new
                        {
                            BrandId = 26,
                            FirstName = "Seth"
                        });
                });

            modelBuilder.Entity("Group4_FinalProject.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "novel",
                            Name = "Novel"
                        },
                        new
                        {
                            CategoryId = "memoir",
                            Name = "Memoir"
                        },
                        new
                        {
                            CategoryId = "mystery",
                            Name = "Mystery"
                        },
                        new
                        {
                            CategoryId = "scifi",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = "history",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Group4_FinalProject.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = "history",
                            Price = 18.0,
                            Title = "1776"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = "scifi",
                            Price = 5.5,
                            Title = "1984"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = "mystery",
                            Price = 4.5,
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = "history",
                            Price = 11.5,
                            Title = "Band of Brothers"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = "novel",
                            Price = 10.99,
                            Title = "Beloved"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = "memoir",
                            Price = 13.5,
                            Title = "Between the World and Me"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = "memoir",
                            Price = 4.25,
                            Title = "Bossypants"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = "scifi",
                            Price = 16.25,
                            Title = "Brave New World"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = "history",
                            Price = 15.0,
                            Title = "D-Day"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = "memoir",
                            Price = 12.5,
                            Title = "Down and Out in Paris and London"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = "scifi",
                            Price = 8.75,
                            Title = "Dune"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = "novel",
                            Price = 9.0,
                            Title = "Emma"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = "scifi",
                            Price = 6.5,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = "novel",
                            Price = 10.25,
                            Title = "Go Tell it on the Mountain"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = "history",
                            Price = 15.5,
                            Title = "Guns, Germs, and Steel"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = "memoir",
                            Price = 14.5,
                            Title = "Hunger"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = "mystery",
                            Price = 6.75,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = "novel",
                            Price = 8.5,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = "mystery",
                            Price = 10.99,
                            Title = "Rebecca"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = "history",
                            Price = 5.75,
                            Title = "The Art of War"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = "mystery",
                            Price = 8.5,
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = "scifi",
                            Price = 12.5,
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = "mystery",
                            Price = 10.99,
                            Title = "The Maltese Falcon"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = "history",
                            Price = 13.75,
                            Title = "The New Jim Crow"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = "memoir",
                            Price = 13.5,
                            Title = "The Year of Magical Thinking"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = "novel",
                            Price = 9.0,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = "memoir",
                            Price = 11.0,
                            Title = "Running With Scissors"
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = "novel",
                            Price = 8.75,
                            Title = "Pride and Prejudice and Zombies"
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = "novel",
                            Price = 9.75,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        });
                });

            modelBuilder.Entity("Group4_FinalProject.Models.ProductBrand", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "BrandId");

                    b.HasIndex("BrandId");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BrandId = 18
                        },
                        new
                        {
                            ProductId = 2,
                            BrandId = 20
                        },
                        new
                        {
                            ProductId = 3,
                            BrandId = 7
                        },
                        new
                        {
                            ProductId = 4,
                            BrandId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            BrandId = 19
                        },
                        new
                        {
                            ProductId = 6,
                            BrandId = 8
                        },
                        new
                        {
                            ProductId = 7,
                            BrandId = 12
                        },
                        new
                        {
                            ProductId = 8,
                            BrandId = 16
                        },
                        new
                        {
                            ProductId = 9,
                            BrandId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            BrandId = 20
                        },
                        new
                        {
                            ProductId = 11,
                            BrandId = 15
                        },
                        new
                        {
                            ProductId = 12,
                            BrandId = 4
                        },
                        new
                        {
                            ProductId = 13,
                            BrandId = 21
                        },
                        new
                        {
                            ProductId = 14,
                            BrandId = 5
                        },
                        new
                        {
                            ProductId = 15,
                            BrandId = 9
                        },
                        new
                        {
                            ProductId = 16,
                            BrandId = 13
                        },
                        new
                        {
                            ProductId = 17,
                            BrandId = 7
                        },
                        new
                        {
                            ProductId = 18,
                            BrandId = 4
                        },
                        new
                        {
                            ProductId = 19,
                            BrandId = 11
                        },
                        new
                        {
                            ProductId = 20,
                            BrandId = 22
                        },
                        new
                        {
                            ProductId = 21,
                            BrandId = 17
                        },
                        new
                        {
                            ProductId = 22,
                            BrandId = 3
                        },
                        new
                        {
                            ProductId = 23,
                            BrandId = 14
                        },
                        new
                        {
                            ProductId = 24,
                            BrandId = 1
                        },
                        new
                        {
                            ProductId = 25,
                            BrandId = 10
                        },
                        new
                        {
                            ProductId = 26,
                            BrandId = 6
                        },
                        new
                        {
                            ProductId = 27,
                            BrandId = 23
                        },
                        new
                        {
                            ProductId = 28,
                            BrandId = 4
                        },
                        new
                        {
                            ProductId = 28,
                            BrandId = 26
                        },
                        new
                        {
                            ProductId = 29,
                            BrandId = 25
                        });
                });

            modelBuilder.Entity("Group4_FinalProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Group4_FinalProject.Models.Product", b =>
                {
                    b.HasOne("Group4_FinalProject.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Group4_FinalProject.Models.ProductBrand", b =>
                {
                    b.HasOne("Group4_FinalProject.Models.Brand", "Brand")
                        .WithMany("ProductBrands")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group4_FinalProject.Models.Product", "Product")
                        .WithMany("ProductBrands")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Group4_FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Group4_FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group4_FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Group4_FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
